# Generated by Django 5.2.4 on 2025-07-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
