# Generated by Django 5.2.4 on 2025-07-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=16)),
                ('cardholder_name', models.CharField(max_length=100)),
                ('expiry_date', models.CharField(max_length=7)),
                ('cvv', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
